//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LagoVista.Uas.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CoreResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LagoVista.Uas.Core.Resources.CoreResources", typeof(CoreResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR:.
        /// </summary>
        internal static string Common_Error {
            get {
                return ResourceManager.GetString("Common_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EKF - Airspeed Variance &gt;1 [{0}].
        /// </summary>
        internal static string Err_AirSpeed {
            get {
                return ResourceManager.GetString("Err_AirSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EKF - Compass Variance &gt; 1 - [{0}].
        /// </summary>
        internal static string Err_Comp {
            get {
                return ResourceManager.GetString("Err_Comp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EKF - Horizontal Position Variance  &gt; 1 - [{0}].
        /// </summary>
        internal static string Err_HPos {
            get {
                return ResourceManager.GetString("Err_HPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EKF - Terrain Altitude Variance &gt; 1 - [{0}].
        /// </summary>
        internal static string Err_TerrAlt {
            get {
                return ResourceManager.GetString("Err_TerrAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EKF - Velocity Variance &gt; 1 - [{0}].
        /// </summary>
        internal static string Err_Velocity {
            get {
                return ResourceManager.GetString("Err_Velocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EKF - Vertical Position Variance &gt; 1 -  [{0}].
        /// </summary>
        internal static string Err_VPos {
            get {
                return ResourceManager.GetString("Err_VPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        internal static string Logging {
            get {
                return ResourceManager.GetString("Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acelerometer .
        /// </summary>
        internal static string Sensor_Accelerometer {
            get {
                return ResourceManager.GetString("Sensor_Accelerometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acelerometer 2.
        /// </summary>
        internal static string Sensor_Accelerometer2 {
            get {
                return ResourceManager.GetString("Sensor_Accelerometer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AHRS.
        /// </summary>
        internal static string Sensor_AHRS {
            get {
                return ResourceManager.GetString("Sensor_AHRS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude Control.
        /// </summary>
        internal static string Sensor_AltitudeControl {
            get {
                return ResourceManager.GetString("Sensor_AltitudeControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attitude Stabilization.
        /// </summary>
        internal static string Sensor_AttitudeStabilization {
            get {
                return ResourceManager.GetString("Sensor_AttitudeStabilization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barometer.
        /// </summary>
        internal static string Sensor_Barometer {
            get {
                return ResourceManager.GetString("Sensor_Barometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compass.
        /// </summary>
        internal static string Sensor_Compass {
            get {
                return ResourceManager.GetString("Sensor_Compass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compass 2.
        /// </summary>
        internal static string Sensor_Compass2 {
            get {
                return ResourceManager.GetString("Sensor_Compass2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Differential Pressure.
        /// </summary>
        internal static string Sensor_DifferentialPressure {
            get {
                return ResourceManager.GetString("Sensor_DifferentialPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geo Fence.
        /// </summary>
        internal static string Sensor_GeoFence {
            get {
                return ResourceManager.GetString("Sensor_GeoFence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS.
        /// </summary>
        internal static string Sensor_GPS {
            get {
                return ResourceManager.GetString("Sensor_GPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ground Truth.
        /// </summary>
        internal static string Sensor_GroundTruth {
            get {
                return ResourceManager.GetString("Sensor_GroundTruth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyrometer 2.
        /// </summary>
        internal static string Sensor_Gryo2 {
            get {
                return ResourceManager.GetString("Sensor_Gryo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyrometer.
        /// </summary>
        internal static string Sensor_Gyro {
            get {
                return ResourceManager.GetString("Sensor_Gyro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laser Position.
        /// </summary>
        internal static string Sensor_LaserPosition {
            get {
                return ResourceManager.GetString("Sensor_LaserPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging.
        /// </summary>
        internal static string Sensor_Logging {
            get {
                return ResourceManager.GetString("Sensor_Logging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission Position.
        /// </summary>
        internal static string Sensor_MissionPosition {
            get {
                return ResourceManager.GetString("Sensor_MissionPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor Control.
        /// </summary>
        internal static string Sensor_MotorControl {
            get {
                return ResourceManager.GetString("Sensor_MotorControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optical Flow.
        /// </summary>
        internal static string Sensor_OpticalFlow {
            get {
                return ResourceManager.GetString("Sensor_OpticalFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Control.
        /// </summary>
        internal static string Sensor_RateControl {
            get {
                return ResourceManager.GetString("Sensor_RateControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RC Receiver.
        /// </summary>
        internal static string Sensor_RCReceiver {
            get {
                return ResourceManager.GetString("Sensor_RCReceiver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse Throttle.
        /// </summary>
        internal static string Sensor_RevThrottle {
            get {
                return ResourceManager.GetString("Sensor_RevThrottle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terrain.
        /// </summary>
        internal static string Sensor_Terrain {
            get {
                return ResourceManager.GetString("Sensor_Terrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XY Position Control.
        /// </summary>
        internal static string Sensor_XYPositionControl {
            get {
                return ResourceManager.GetString("Sensor_XYPositionControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yaw Position.
        /// </summary>
        internal static string Sensor_YawPosition {
            get {
                return ResourceManager.GetString("Sensor_YawPosition", resourceCulture);
            }
        }
    }
}
